<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--SEO--><title>JinyDev | PHP</title>
            <meta name="title" content="PHP" /><meta name="keyword" content="jinyphp, php, 객체지향, oop, class" /><!--부트스트랩4-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <style>
            img {
                max-width:100%;
            }
        </style>

        <link rel="stylesheet" href="/assets/highlight.css">
        <link rel="stylesheet" href="/assets/style.css">

        <script data-ad-client="ca-pub-3321560028329475" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        
    </head>
    <body>
        <!--네비게이션--><!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">JinyDev</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/php">PHP</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://mysql.jiny.dev">Mysql</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://git.jiny.dev">Git</a>
          </li>
        </ul>
      </div>
    </div>
</nav><header>
  <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <img src="/php/img/num1.jpg">
      </div>
      <div class="col-lg-9">
        <h1 class="display-3">PHP</h1>
        <h2>PHP로 시작하는 프로그래밍 입문</h2>
        <p>웹서비스 개발을 위한 서버사이드 언어 입니다. </p>
   
    </p>
      </div>
    </div>
  </div>
</div>
</header>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Post Content Column -->
        <div class="col-lg-9">
          <section>
            <h3 id="172-예외">17.2 예외</h3>
<p>예외라는 말은 프로그램 실행 도중 예상치 않은 동작이나 불확실한 처리로 발생할 수 있는 부분을 예상하여 오류까지도 같이 처리를 하는 코딩 방법입니다. try{} catch {}의 문법과 별도의 예외 처리를 위한 클래스 등이 존재합니다.</p>

<p>예외 처리는 PHP스크립트가 실행하면서 오류가 발생했을 때 처리할 수 있는 로직을 만들어 넣을 수 있는 기술입니다. 예외 처리 개념은 PHP 5.x 이전에는 도입되지 않았습니다.</p>

<p>오류의 경우는 프로그램의 문제가 발생하면 오류를 통보하고 프로그램이 중단됩니다. 하지만, 예외는 갑작스러운 오류 발생 시 스크립트를 그냥 종료하는 것이 아니라 별도의 처리 루틴을 통해 안전하게 프로그램을 마칠 수 있도록 합니다.</p>

<p><br /></p>
<hr />

<h3 id="1721-exception-클래스">17.2.1 Exception 클래스</h3>
<p>PHP는 예외 처리를 위해서 특별한 Exception 클래스를 제공합니다. 예외 처리 클래스는 예외 발생 시 심각한 오류를 안전한 경로로 우회하여 처리할 수 있도록 도와줍니다.</p>

<p>예외 처리 클래스 Exception도 new 키워드를 통해 인스턴스를 생성하여 사용할 수 있습니다. Exception 클래스는 오류 코드와 메시지를 전달하고 값을 처리할 수 있는 추가 메서드를 지원합니다.</p>

<p>예제 파일 exception-01.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	$msg = "예외 클래스 오류 발생";
	$code = 444;
	$e = new Exception($msg,$code);

	echo "예외 코드 = ".$e-&gt;getCode();
	echo "&lt;br&gt;";
	echo "예외 메시지 = ".$e-&gt;getMessage();
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>예외 코드 = 444
예외 메시지 = 예외 클래스 오류 발생
</code></pre></div></div>

<p>예외 Exception 클래스 구조와 인터페이스는 다음과 같습니다.</p>

<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>Exception {
/* Properties */
protected string $message ;
protected int $code ;
protected string $file ;
protected int $line ;

/* Methods */
public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )
final public string getMessage ( void )
final public Throwable getPrevious ( void )
final public mixed getCode ( void )
final public string getFile ( void )
final public int getLine ( void )
final public array getTrace ( void )
final public string getTraceAsString ( void )
public string __toString ( void )
final private void __clone ( void )
}
</code></pre></div></div>

<p>예외 처리가 발생하면 PHP 엔진은 Exception 클래스로 예외를 발생한 부분을 처리하게 됩니다.</p>

<p>PHP 7.x에서는 Exception 클래스는 throwable 인터페이스를 따릅니다.</p>

<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>Throwable {
/* Methods */
abstract public string getMessage ( void )
abstract public int getCode ( void )
abstract public string getFile ( void )
abstract public int getLine ( void )
abstract public array getTrace ( void )
abstract public string getTraceAsString ( void )
abstract public Throwable getPrevious ( void )
abstract public string __toString ( void )
}
</code></pre></div></div>

<p><br /></p>
<hr />

<h3 id="1722-throw">17.2.2 throw</h3>
<p>throw 키워드를 이용하여 사용자가 직접 예외를 발생할 수 있습니다. 예외가 발생하면 PHP는 코드 실행을 중지됩니다.</p>

<p>throw 키워드는 Exception과 관련 서브 클래스에서만 사용이 가능한 키워드입니다.</p>

<ul>
  <li>Exception</li>
  <li>ErrorException</li>
</ul>

<p>예제 파일 exception-02.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	throw new Exception("강제적 예외 발생");
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>[Sun May 14 16:21:35 2017] ::1:55806 [500]: /jinyphp/exception-02.php - Uncaught Exception: 강제적 예외 발생 in C:\php-7.1.4-Win32-VC14-x86\jinyphp\exception-02.php:2
Stack trace:
#0 {main}
thrown in C:\php-7.1.4-Win32-VC14-x86\jinyphp\exception-02.php on line 2
</code></pre></div></div>

<p>위의 예제는 예외 발생 처리 예입니다. throw 명령으로 사용자가 직접 예외를 발생할 수 있습니다.</p>

<p><br /></p>
<hr />

<h3 id="1723-exception-상속">17.2.3 Exception 상속</h3>
<p>예외 처리 Exception 클래스를 상속받아 새로운 에외 처리 클래스를 직접 만들어서 사용할 수도 있습니다. 새로운 예외 처리는 클래스는 기존의 exception 함수를 상속받아서 생성을 합니다.</p>

<p>|문법|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>class divException extends exception {}
</code></pre></div></div>

<p>예제 파일 exception-03.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	class aaaEx extends exception
	{
		public function showErr($msg)
		{
			echo $msg;
		}
	}

	$msg = "예외 클래스 오류 발생";
	$code = 444;
	$e = new aaaEx($msg,$code);

	$e-&gt;showErr("Exception을 상속합니다.");
	echo "&lt;br&gt;";
	echo "예외코드 = ".$e-&gt;getCode();
	echo "&lt;br&gt;";
	echo "예외메시지 = ".$e-&gt;getMessage();
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>Exception을 상속합니다.
예외 코드 = 444
예외 메시지 = 예외 클래스 오류 발생
</code></pre></div></div>

<p>위의 예제는 예외 처리 클래스 상속에 대한 예입니다. 기존 exception 예외 클래스를 상속받아 새로운 예외 처리 클래스를 만들어서 사용할 수 있습니다.</p>

<p><br /></p>
<hr />

<h3 id="1724-예외-포착">17.2.4 예외 포착</h3>
<p>개발자는 예외 처리에 대해서 수동적인 방어 보다는 능동적인 방어가 필요합니다. 적극적으로 예외가 발생될 것을 예측하여 프로그램 코드를 작성해야 합니다.</p>

<p>PHP 언어는 예외를 포착할 수 있는 try ~ catch 명령 키워드를 제공합니다. try~catch는 C++이나 Java 등에서 일찌감치 예외 처리를 위해 사용하던 문법입니다. PHP 5.x 이후부터는 이와 비슷한 스타일로 예외 처리 문장을 만들 수 있습니다.</p>

<p>프로그램이 동작할 때 예외가 발생할 가능성이 있다고 하면 try {} catch {} 명령으로 예외 발생을 대비하는 것이 좋습니다.</p>

<p>try~catch는 2개의 영역으로 나누어져 있습니다.</p>

<p>|문법|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>try {
	예외가 발생할 가능성이 있는 내용들을 코딩합니다.
} catch (클래스명 $변수명) {
	예외가 발생될 경우 처리할 내용들
}
</code></pre></div></div>

<p>try { } 부분<br />
try 본문 안에는 예외가 발생될 가능성이 높은 코드를 작성하는 영역입니다. 특별한 코드가 이니라 정상적으로 수행하고자 하는 코드를 작성합니다. 만일 이 코드들이 예외를 발생할 여지가 있는 경우 try{} 로 코드를 감싸서 실행하는 것입니다.</p>

<p>오류 예외가 발생되지 않으면 큰 문제나 의미 없이 코드가 실행될 것입니다. 만일 try 안에 있는 코드에 예외가 발생하면 코드 실행을 중단하게 됩니다. 그리고 catch 부분의 코드를 수행합니다.</p>

<p>catch {} 부분<br />
catch (클래스명 $변수명) { }은 try{} 본문에 예외가 포착되었을 때 처리되는 내용들입니다.</p>

<p>예외가 발생할 때 Excetion 클래스를 통해 예외 상태나 메시지를 받아올 수 있습니다. Exception 클래스는 예외를 처리할 수 있는 다양한 프로퍼티와 메서드를 가지고 있습니다.</p>

<p>|문법|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>catch(Exception $err){
	echo $err-&gt;getMessage();
} 
</code></pre></div></div>

<p>예외 발생 시 Exception 클래스로 생성된 인스턴스를 받습니다. 생성된 인스턴스로 Exception 메서드를 실행할 수 있습니다.</p>

<p>예제 파일 exception-04.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	try {
	
		throw new Exception("강제적 예외 발생");

	} catch(Exception $err){
		// Try {} 부분에 연산 오류로 인하여 예외 처리가 발생됨
		echo "예외 처리 발생 :".$err-&gt;getMessage();
	} 
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>예외 처리 발생: 강제적 예외 발생
</code></pre></div></div>

<p>위의 예제는 try~catch 동작에 대한 예입니다. try {} 본문 안에서 강제적으로 throw 명령을 통해 개발자가 직접 예외를 발생합니다. 예외가 발생되면catch{} 안의 내용이 실행됩니다. catch 실행 시 예외 처리 클래스 exception 객체를 동시에 생성하여 catch 내부로 전달합니다.</p>

<p>catch 내에서는 exception 클래스로 생성된 객체를 접근하여 메시지 및 상태를 체크할 수 있습니다.</p>

<p><br /></p>
<hr />

<h3 id="1725-다중-catch">17.2.5 다중 catch</h3>
<p>만일 예외 처리의 유형이 다양한 경우 catch를 연결하여 사용 가능합니다.</p>

<p>|문법|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>try {
	예외가 발생할 가능성이 있는 내용들을 코딩합니다.
} catch (클래스명 $변수명) {
	예외가 발생될 경우 처리할 내용들
} catch (클래스명 $변수명) {
	예외가 발생될 경우 처리할 내용들
}
</code></pre></div></div>

<p>catch는 위의 표현처럼 계속 체인 형태로 연결하여 사용할 수 있습니다.</p>

<p>예제 파일 exception-05.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	try {
		$servername = "localhost";
		$dbname = "testDB";
		$username = "jiny";
		$pasword = "abcd1234";

		$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
	
	} catch (PDOException $e) {
		echo "PDO 오류";

	} catch (Exception $e) {
		echo "일반예외";
	}
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>PDO 오류
</code></pre></div></div>

<p>위의 예제는 다수의 catch 처리를 위한 실험입니다. 예외가 발생되면 예외 상태에 따라서 상항별로 catch 로 분기하여 처리됩니다.</p>

<p><br /></p>
<hr />

<h3 id="1726-finally">17.2.6 finally</h3>
<p>finally { } 부분은 PHP 5.5에서 도입된 기능으로 try 부분이나 catch부분 처리가 끝나고 처리할 내용을 추가로 정의할 수 있습니다. finally {}는 독립적으로 사용을 할 수 없고 반드시 try ~ catch문 뒤에 소속되어 사용 가능합니다. 즉, 종속된 기능 명령어 입니다.</p>

<p>사용 문법</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>try {
	예외가 발생할 가능성이 있는 내용들을 코딩합니다.
} catch (클래스명 $변수명) {
	예외가 발생될 경우 처리할 내용들
} finally {
	예외 발생 여부와 상관없이 처리할 내용
}
</code></pre></div></div>

<p>예제 파일 exception-06.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	try {
	
		throw new Exception("강제적 예외 발생");

	} catch(Exception $err){
		// Try {} 부분에 연산오류로 인하여 예외 처리가 발생됨
		echo "예외 처리 발생 :".$err-&gt;getMessage();
	} finally {
		// try {} 또는 catch(){} 부분의 처리 후에 처리가 됩니다.
		echo "&lt;br&gt;";
		echo "finally 연산 종료";
	}
?&gt;</span>
</code></pre></div></div>

<p>결과</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>예외 처리 발생: 강제적 예외 발생
finally 연산 종료
</code></pre></div></div>

<p>위의 예제는 final 에 대한 예입니다. 예외가 발생하면 catch 부분을 수행합니다. 그리고 catch 부분을 처리 후에 finally {} 부분을 실행합니다.</p>

<p><br /></p>
<hr />

<h3 id="1727-전역-예외-처리">17.2.7 전역 예외 처리</h3>
<p>try~catch로 처리하지 못한 예외가 있을 수도 있습니다. 이런 경우 전역 예외 처리를 통해 예상치 못한 예외도 포착할 수 있습니다.</p>

<p>|관련함수|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>callable set_exception_handler ( callable $exception_handler )
</code></pre></div></div>

<p>set_exception_handler(); 내장 함수를 통하여 전역 예외 처리를 등록할 수 있습니다.</p>

<p>|관련함수|</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>bool restore_exception_handler ( void )
</code></pre></div></div>

<p>restore_exception_handler(); 내장 함수는 설정한 전역 처리기를 복원합니다.</p>

<p>예제 파일 exception-07.php</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code><span class="cp">&lt;?php
	// 전역 예외 처리기를 등록합니다.
	set_exception_handler(function(Exception $e){
		echo "전역 예외 처리 포착&lt;br&gt;";
		echo "예외 메시지 = ".$e-&gt;getMessage();
	});

	throw new Exception("강제적 예외 발생");

	// 설정한 전역 처리기를 복원합니다.
	restore_exception_handler();
?&gt;</span>
</code></pre></div></div>

<p>결과)</p>
<div class="language-html highlighter-rouge"><div class="highlight"><pre class="syntax"><code>전역 예외 처리 포착
예외 메시지 = 강제적 예외 발생
</code></pre></div></div>

<p>위의 예제는 전역 예외 처리에 대한 예입니다. set_exception_handler() 함수를 통해 적역 예외 처리 함수를 등록합니다.</p>

<p><br /><br /></p>

          </section>
            
        </div>

        <!-- Sidebar Column -->
        <div class="col-md-3">
          <aside><ul class="list-group">
    <li class="list-group-item list-group-item-dark">Site Menu</li>
    <li class="list-group-item"><a href="/php/php">소개</a></li>
    <li class="list-group-item"><a href="/php/install">설치</a></li>
    <li class="list-group-item"><a href="/php/basic">기본문법</a></li>

    <li class="list-group-item"><a href="/php/function">함수</a></li>

    <li class="list-group-item"><a href="/php/oop">객체지향</a></li>
</ul>
<br>
</aside>
            
        </div>

    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
        <footer>  <!-- Footer -->
  <footer class="py-3 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; jinydev 2017~2020</p>
    </div>
    <!-- /.container -->
  </footer></footer>  
        
        <!--부트스트랩4-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-160048106-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-160048106-1');
        </script>

    </body>

</html>